# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f7f164cba3c3bd4dfb9ebabd27b35f41ad41372b3f8cbf66c947280d7edc7fefc13c5b3ce274fe4c00b63fdd7fefc52a38dfb03d39971967508563999d2d46

test:
  secret_key_base: 1316e28eda60bf589820762ddb4c7b24f1dba77d4e56b99cdd94bd0d886ac13165d9af4934cd8074ce1b2bf1421b639c1f413e366cb1d3a71016dbf29f745065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
